### PR TITLE
Lyrics in chords

### PR DESCRIPTION
**Pull request by th-we**
I rebased ~~#124~~ #122 and added a test for #124. I'd close #124 and #122 and merge this one.

### CODE REVIEW

**Comment by th-we** [comment]
Oh well, I got confused with the commits and pull requests again – sorry for mixing up #122 and #124. I'll check the offset related commit now – that's the one I actually rebased.

**Comment by annplaksin** [comment]
Is it possible to get rid of the two commits for #122 ?
The rest looks fine to me.

**Comment by rettinghaus** [comment]
If I'm not mistaken, you merged the changes from #122 and #124 without changing the version number? Looks fine to me.

**Comment by th-we** [comment]
Yeah, give me some time to sort it out. I shouldn't be doing to many things in parallel.

**Comment by ahankinson** [comment]
I'm still not clear what a syllable on a chord means, musically, but 🤷‍♂

**Comment by rettinghaus** [comment]
@th-we I'm still a bit confused: this PR combines #122 and #124 with some lines from you for testing. 
@annplaksin Are you ok with this, or would you prefer three separate PRs?

**Comment by annplaksin** [comment]
Nope, the changes changes seem fine to me. Would you like to merge @rettinghaus ?

**Pull request merged**
