### PR TITLE
do not duplicate fermatas on rests

### LINKED ISSUE #89: Fermatas over rests get exported twice
When fermatas are placed over rests in Sibelius, they are encoded twice in the MEI output, both as an attribute within the rest element, and separately as a fermata element. This doesn't happen when fermatas are placed above notes, which are only encoded once as a separate fermata element.

To be consistent with how notes are treated, can fermatas above rests only be encoded as a fermata element, please.

```
<measure xml:id="m-1176" n="40">
							<staff xml:id="m-1177" n="1">
								<layer xml:id="m-1178" n="1">
									<note xml:id="m-1179" dur="breve" dur.ges="2048p" layer="1" oct="4" oct.ges="3" pname="d" pnum="50" staff="1" stem.dir="down">
										<verse xml:id="m-1187" n="1">
											<syl xml:id="m-1188" wordpos="t">e</syl>
										</verse>
									</note>
									<note xml:id="m-1180" dur="1" dur.ges="1024p" layer="1" oct="4" oct.ges="3" pname="e" pnum="52" staff="1" stem.dir="down">
										<verse xml:id="m-1189" n="1">
											<syl xml:id="m-1190" wordpos="i">la</syl>
										</verse>
									</note>
									<note xml:id="m-1181" artic="stacc" dur="1" dur.ges="1024p" layer="1" oct="4" oct.ges="3" pname="g" pnum="55" staff="1" stem.dir="down">
										<verse xml:id="m-1191" n="1">
											<syl xml:id="m-1192" wordpos="i">ue</syl>
										</verse>
									</note>
									<note xml:id="m-1182" dur="1" dur.ges="1024p" layer="1" oct="4" oct.ges="3" pname="a" pnum="57" staff="1" stem.dir="down">
										<verse xml:id="m-1193" n="1">
											<syl xml:id="m-1194" wordpos="m">ri</syl>
										</verse>
									</note>
									<note xml:id="m-1184" artic="stacc" dur="1" dur.ges="1024p" layer="1" oct="4" oct.ges="3" pname="a" pnum="57" staff="1" stem.dir="down">
										<verse xml:id="m-1195" n="1">
											<syl xml:id="m-1196" wordpos="t">te</syl>
										</verse>
									</note>
								</layer>
							</staff>
							<staff xml:id="m-1197" n="2">
								<layer xml:id="m-1198" n="1">
									<note xml:id="m-1199" dur="breve" dur.ges="2048p" layer="1" oct="3" oct.ges="2" pname="g" pnum="43" staff="2" stem.dir="up">
										<verse xml:id="m-1204" n="1">
											<syl xml:id="m-1205" wordpos="t">mour</syl>
										</verse>
									</note>
									<rest xml:id="m-1200" dur="long" dur.ges="4096p" fermata="above" />
								</layer>
							</staff>
							<staff xml:id="m-1206" n="3">
								<layer xml:id="m-1207" n="1">
									<note xml:id="m-1208" dur="breve" dur.ges="2048p" layer="1" oct="3" oct.ges="2" pname="g" pnum="43" staff="3" stem.dir="up" />
									<rest xml:id="m-1209" dur="long" dur.ges="4096p" />
								</layer>
							</staff>
							<fermata xml:id="m-1183" form="norm" layer="1" shape="angular" staff="1" startid="#m-1182" />
							<fermata xml:id="m-1201" form="norm" layer="1" shape="curved" staff="2" startid="#m-1200" />
						</measure>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
closes #89

### CODE REVIEW

**Comment by annplaksin** [comment]
Does someone have a test file for that?

**Comment by rettinghaus** [comment]
See [here](https://ddmal.music.mcgill.ca/mei-test-set/MEI-test-set/articulations.html#fermatas.mei). 
Only the rest at the end has an extra `@fermata`.

**Comment by th-we** [comment]
@rettinghaus In that case, the two fermatas are deliberately input in Sibelius:

grafik

But [the Sibelius file](https://github.com/DDMAL/mei-test-set/blob/gh-pages/MEI-test-set/sibelius-files/articulations/fermatas.sib) crashes the current Sibmei for reason other than two fermatas on the same rest, so we should use that as the basis for a new test case.

**Comment by th-we** [comment]
OK, created a test file.

[fermatas.sib.zip](https://github.com/music-encoding/sibmei/files/4483405/fermatas.sib.zip)

Three systems with all the same fermatas so we can re-use the same test for all of them.

grafik

Anyone feeling like writing tests?

**Comment by th-we** [comment]
Update: More comprehensive test set:

grafik

[fermatas.sib.zip](https://github.com/music-encoding/sibmei/files/4485237/fermatas.sib.zip)

**Comment by annplaksin** [comment]
I am currently looking into the crash... and I just found that little comment: ;-)
```javascript
function GenerateFermata (bobj) {
    //$module(ExportGenerators.mss)
    /* Note rests can have multiple fermatas in Sibelius,
        but this is currently not supported.
        Also, fermatas added as symbols are not yet handled.
    */
```
When I got rid of the crash, we will see how much of the work is done. But it might be wise to rework the fermata stuff in the future. 
But I would like to wait with handling the symbol fermatas until after my planned reworking of `ProcessSymbol()`

**Comment by th-we** [comment]
@annplaksin I fully agree. That might lead to doing the work twice.

**Comment by annplaksin** [comment]
I solved the crash and added a test to make sure, rests have no `@fermata` attributes.
@rettinghaus Please see my pull request to this branch.

Everything else, like fermata symbols, should be added after reworking the symbols.

**Comment by annplaksin** [comment]
Just to mention, #162 contains the changes made here and adds fermatas as sysmbols.

**Pull request closed without merging**
