### PR TITLE
Update libmei to fix "tail" bug

### PR DESCRIPTION
**Pull request by th-we**
See https://github.com/DDMAL/libmei/pull/117

@ahankinson Could you have a look at [my pull requests] on the libmei repo so we can get in synch again?

### CODE REVIEW

**Comment by ahankinson** [comment]
Is there an issue that describes the bug? I can’t really tell what triggers it...

**Comment by th-we** [comment]
As `.SetTail()` is currently only used on a self-closing `<lb>` element., this is not triggered. But I'm experimenting with mixing text and elements, like:

    p = libmei.P();
    name = libmei.PersName();
    libmei.SetText(name, 'Joe');
    libmei.AddChild(p, name);
    name.SetTail(' sings');

Expected output:

    <p><persName>Joe</persName>sings</p>

Actual output is something like:

    <p><persName>Joe                 sings</persName></p>

(Handling of spaces when serializing will be another issue to tackle later.)

**Comment by ahankinson** [comment]
Sounds OK. I wouldn’t expect anything to add extra spaces that were not present in the original.

**Comment by th-we** [comment]
Thanks! Spaces are added because of indentation. Maybe we could add something like `libmei.SetIndent(element, false);` to suppress indentation for elements where it's undesired.

**Comment by ahankinson** [comment]
If I see `name.SetTail(' sings');` then I would expect the output to be `<p><persName>Joe</persName> sings</p>` -- that the space in the original would be preserved in the XML output. Likewise, if there were no spaces, then I would not expect sibmei to inject a space when outputting elements, and the output (when rendered without tags) would be `Joesings`. That's the way HTML treats tags AFAIK. 

The spaces for the tail can probably be handled by removing the 'tabs' bit, which doesn't really make sense for a tail fragment.

**Pull request merged**
