### PR TITLE
Pr/release 2.2.0 fixed

### PR DESCRIPTION
**Pull request by th-we**
O.K., merged an old state of the develop branch for the last pull request. Added the missing stuff now.

### CODE REVIEW

**Comment by th-we** [comment]
Found some tests are still crashing Sibelius, so better wait until I fixed that.

**Comment by ahankinson** [comment]
OK; I won't merge now, but will wait. Just let me know.

**Comment by th-we** [comment]
I did quite some changes to the tests.  The major challenge was again to make them work on Sibelius Ultimate without crashing. ManuScript seems to become more likely to crash Sibelius with newer releases, especially when opening and closing scores.

For more details, see the commit message of 2e6c302.

To make sure it works on the Mac with your version of Sibelius – could you please run the tests?  `nmp test` still fails three tests concerning lyrics, but that's expected. These are not regressions but missing features. A suggestion how to sensibly separate tests for features that were not implemented yet is very welcome.

**Comment by ahankinson** [comment]
It's easier if I merge to master and then check the tests. I'll do that now.

**Pull request merged**
