### PR TITLE
Changes in basic functions of sibmei

### PR DESCRIPTION
**Pull request by annplaksin**
Out of the development for the CMO project, I changed some other things in sibmei:
- Rewritten ProcessBeam()
- Added changing time signature
- Bugfixing in ConvertAccidental()
- Bugfixing in GenerateLayer() to get also symbols and lines at the beginning of measures correctly
- Corrected connectors in ProcessLyrics() 
- Added referencing with @startid and @endid in symbols, text, and lines
- Added processing of symbols on system staff
- Added more lines
- Added handling for hidden special barlines

Furthermore, I've added an approach for a generic handling of great numbers of user-defined symbols and text styles by using global variables.

### CODE REVIEW

**Comment by ahankinson** [comment]
Thank you very much. Since this is such a large change, and it's based on a relatively old version of sibmei, could I ask that you merge your changes with the current develop branch and verify that it still works properly on your machine?

I will also switch it to be based against the `develop` branch, since that is where active development takes place for this.

**Comment by ahankinson** [comment]
It also looks like there is a significant amount of specialized code in here for your particular project. Is it possible to separate this out from the bug fixes and generally-applicable contributions?

**Comment by ahankinson** [comment]
After doing a review of this, I think there are some valuable contributions here, but they are hard to understand in such a large pull request, since some changes get overwritten by others. So I would recommend the following:

1) Please remove any CMO-specific encoding commits.
2) For the changes you would like to contribute, please 'squash' them into a single commit so that I can check the actual changes that will be merged in. 

It would probably be best if you submit it under a different pull request, but I will let you decide.

**Comment by annplaksin** [comment]
Thanks for your short review.
I will try to follow your instructions as good as possible when I stopped struggeling with making pull requests. I'm still not familiar with making pull requests, sorry.
Hopefully, the next try will be suitable for you.

**Pull request closed without merging**
