### PR TITLE
fix order in header

### LINKED ISSUE #158: encoding error in head
SIBMEI places the `encodingDesc` after the `workDesc`, which isn't allowed.

### PR DESCRIPTION
**Pull request by rettinghaus**
closes #158

### CODE REVIEW

**Comment by rettinghaus** [comment]
This has been fixed already in the develop branch, but it is also wrong in MEI3. 
So I suppose a last bugfix would be good here.

**Comment by th-we** [comment]
Should we create a maintenance branch for v3 and apply this PR on that branch?  Naming suggestion: `mei3`. A little confusing because the current version is actually sibmei 2.3.0, but I think `mei3` is clearer than `sibmei2`.

**Comment by rettinghaus** [comment]
Sounds like a good idea, but this PR goes to master branch, so I would merge it first and then make a new branch for this. 
Speaking of branches: shouldn't we rename master to main, and do we need a main branch at all, if we have dedicated branches for each version of MEI?

**Comment by annplaksin** [comment]
One short question: Why would you like to still maintain the mei 3 version? I think the last release announced the coming upgrade to MEI 4. The Guidlines of v3 already deem the version outdated and refer to MEI 4... and lets see how long we have until the next MEI version will be released.

It's not that I want to spoil anything, I am just thinking about the effort to maintain two versions. Maybe it is better to stick with making a clean cut and finally release the version 4.
Just my two cents...

**Comment by rettinghaus** [comment]
@annplaksin It's not we really maintain it, but we should make sure it always produces valid output. If something pops up elsewhere we could easily provide a bugfix release then.

**Comment by bwbohl** [comment]
Although requested as reviewer, I think I'm not the right person to do this here… @th-we ?

**Comment by bwbohl** [comment]
thx @th-we

**Pull request merged**
